stages:
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  stage: test
  image: python
  variables:
    YTDL_TEST_SET: core
  script:
    - pip3 install nose
    - ./devscripts/run_tests.sh
