name: Build script staging

on:
  push:
    branches:
      - master
    workflow_dispatch:
      inputs: {}

env:
  python_version: 3.8.5

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      latest_version: ${{ steps.prepare.outputs.latest_version }}
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
          sudo ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
          sudo apt update
          sudo env DEBIAN_FRONTEND=noninteractive apt install -y tzdata
      - name: Prepare files
        id: prepare
        run: |
          mkdir artifacts
          export LATEST_VERSION="$(date)"
          echo "${LATEST_VERSION}" > artifacts/LATEST_VERSION
          echo "::set-output name=latest_version::${LATEST_VERSION}"

          echo "from __future__ import unicode_literals
          __version__ = '${LATEST_VERSION}'
          " > youtube_dl/version.py
      - name: Upload artifacts for the next steps
        uses: actions/upload-artifact@v2
        with:
          name: ytdl-base
          path: |
            youtube_dl/version.py
            artifacts/
  build-linux:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v2
      - name: Download base
        uses: actions/download-artifact@v2
        with:
          name: ytdl-base
      - name: Set up Python ${{ env.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.python_version }}
      - name: Install deps
        run: |
          sudo ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
          sudo apt update
          sudo env DEBIAN_FRONTEND=noninteractive apt install -y curl zip make git gawk pandoc tzdata
      - name: Build patched YTDL for Linux
        run: |
          make youtube-dl youtube-dl.tar.gz
          mv youtube-dl artifacts/
          mv youtube-dl.tar.gz artifacts/
      - name: Upload artifacts for the next steps
        uses: actions/upload-artifact@v2
        with:
          name: ytdl-linux
          # README.md (or any other files in the repo) is required
          # to prevent upload-artifacts to find LCA
          path: |
            artifacts/
            README.md
  build-windows:
    runs-on: windows-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v2
      - name: Download base
        uses: actions/download-artifact@v2
        with:
          name: ytdl-base
      - name: Set up Python ${{ env.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.python_version }}
      - name: Install deps
        run: |
          pip install --upgrade pyinstaller
      - name: Build patched YTDL for Windows
        run: |
          python -m PyInstaller `
              --onefile --console --distpath . `
              --hidden-import codecs `
              -n youtube-dl youtube_dl\__main__.py
          Move-Item youtube-dl.exe artifacts/
      - name: Upload artifacts for the next steps
        uses: actions/upload-artifact@v2
        with:
          name: ytdl-windows
          # README.md (or any other files in the repo) is required
          # to prevent upload-artifacts to find LCA
          path: |
            artifacts/
            README.md
  prepare-artifacts:
    runs-on: ubuntu-latest
    needs: [prepare, build-linux, build-windows]
    env:
      LATEST_VERSION: ${{ needs.prepare.outputs.latest_version }}
    steps:
      - name: Download builds for Linux
        uses: actions/download-artifact@v2
        with:
          name: ytdl-linux
      - name: Download builds for Windows
        uses: actions/download-artifact@v2
        with:
          name: ytdl-windows
      - name: Install deps
        run: |
          sudo apt update
          sudo env DEBIAN_FRONTEND=noninteractive apt install -y jq
      - name: Prepare artifacts
        run: |
          FILEHASH_BIN="$(sha256sum artifacts/youtube-dl | awk '{print $1}')"
          FILEHASH_TAR="$(sha256sum artifacts/youtube-dl.tar.gz | awk '{print $1}')"
          FILEHASH_EXE="$(sha256sum artifacts/youtube-dl.exe | awk '{print $1}')"
          echo '{"versions":{}}' | jq ".latest=\"${LATEST_VERSION}\"" \
            | jq ".versions[\"${LATEST_VERSION}\"].bin=[\"https://nao20010128nao.github.io/ytdl-patched/youtube-dl\",\"${FILEHASH_BIN}\"]" \
            | jq ".versions[\"${LATEST_VERSION}\"].tar=[\"https://nao20010128nao.github.io/ytdl-patched/youtube-dl.tar.gz\",\"${FILEHASH_TAR}\"]" \
            | jq ".versions[\"${LATEST_VERSION}\"].exe=[\"https://nao20010128nao.github.io/ytdl-patched/youtube-dl.exe\",\"${FILEHASH_EXE}\"]" \
            | tee artifacts/versions.json
          echo "Upload artifacts here"
      - name: Upload artifacts for the next steps
        uses: actions/upload-artifact@v2
        with:
          name: ytdl-artifacts
          # README.md (or any other files in the repo) is required
          # to prevent upload-artifacts to find LCA
          path: |
            artifacts/
            README.md
  windows-test:
    needs: build-windows
    runs-on: windows-${{ matrix.windows }}
    strategy:
      matrix:
        windows: [2016, 2019]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: ytdl-windows
      - name: youtube-dl --help and --version
        run: |
          .\artifacts\youtube-dl.exe --help
          .\artifacts\youtube-dl.exe --version
      - name: Download some videos
        run: |
          .\artifacts\youtube-dl.exe `
              https://www.youtube.com/watch?v=XEY7UQJxw-o `
              https://twitter.com/twetchapp/status/1311686520793829376
  ubuntu-test:
    needs: build-linux
    runs-on: ubuntu-${{ matrix.ubuntu }}
    strategy:
      matrix:
        ubuntu: ["20.04", "18.04", "16.04"]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: ytdl-linux
      - name: youtube-dl --help and --version
        run: |
          chmod a+x ./artifacts/youtube-dl
          ./artifacts/youtube-dl --help
          ./artifacts/youtube-dl --version
      - name: Download some videos
        run: |
          ./artifacts/youtube-dl \
              https://www.youtube.com/watch?v=XEY7UQJxw-o \
              https://twitter.com/twetchapp/status/1311686520793829376
