name: Windows build trial

on:
  push:
    branches:
      - master

jobs:
  build-win:
    runs-on: windows-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install deps
      run: |
        python -m pip install py2exe pyinstaller
    - name: Build using py2exe
      run: |
        python -m py2exe setup.py
    - name: Build using pyinstaller
      run: |
        python -m pyinstaller __main__.py
