name: Windows build trial

on:
  push:
    branches:
      - master

jobs:
  build-win:
    runs-on: windows-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install deps
      run: |
        python -m pip install py2exe pyinstaller
    - name: Build using py2exe
      continue-on-error: true
      run: |
        python -m py2exe setup.py
        ls
    - name: Build using pyinstaller
      continue-on-error: true
      run: |
        python -m PyInstaller --distpath . -n youtube-dl -c youtube_dl/__main__.py
        ls ./youtube-dl
        ./youtube-dl/youtube-dl --simulate https://youtu.be/0d4-azwtoHc
    - name: Test WSL
      continue-on-error: true
      run: |
        curl -Lo ubuntu.appx https://aka.ms/wslubuntu2004
        Add-AppxPackage ubuntu.appx
        bash apt update
        bash apt install wget
        bash wget -qO- checkip.amazonaws.com
  build-linux:
    runs-on: ubuntu-20.04
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install deps
      run: |
        mkdir -p wine-root/drive_c/py/ wine-root/drive_c/dist/
        export WINEPREFIX="$(realpath wine-root/)" WINEARCH=win64
        sudo dpkg --add-architecture i386
        wget -O- https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
        sudo add-apt-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ focal main'
        sudo apt update
        sudo apt install --no-install-recommends -y wine64
        wget https://www.python.org/ftp/python/3.8.5/python-3.8.5-embed-amd64.zip
        unzip -d wine-root/drive_c/py/ python-3.8.5-embed-amd64.zip
        wget https://bootstrap.pypa.io/get-pip.py -O wine-root/drive_c/py/get-pip.py
        wine64-stable "C:\\py\\python.exe" "C:\\py\\get-pip.py"
        wine64-stable "C:\\py\\Scripts\\pip.exe" install pyinstaller
        wine64-stable "C:\\py\\python.exe" -m PyInstaller --distpath "C:\\dist\\" -n youtube-dl -c youtube_dl/__main__.py
        ls "$WINEPREFIX/drive_c/dist/youtube-dl"
        file "$WINEPREFIX/drive_c/dist/youtube-dl"
