name: Windows build trial

on:
  push:
    branches:
      - master

jobs:
  build-win:
    runs-on: windows-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install deps
      run: |
        python -m pip install py2exe pyinstaller
    - name: Build using py2exe
      continue-on-error: true
      run: |
        python -m py2exe setup.py
        ls
    - name: Build using pyinstaller
      continue-on-error: true
      run: |
        python -m PyInstaller --distpath . -n youtube-dl -c youtube_dl/__main__.py
        ls ./youtube-dl
        ./youtube-dl/youtube-dl --simulate https://youtu.be/0d4-azwtoHc
    - name: Test Docker
      run: |
        docker pull alpine
        docker run --rm --name test alpine
        docker exec test apk add --no-cache wget
        docker exec test wget -qO- checkip.amazonaws.com
