name: Upload to IPFS

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs: {}

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master
      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Install IPFS
        run: |
          sudo snap install ipfs
          ipfs init
          ipfs cat /ipfs/QmQPeNsJPyVWPFDVHb77w8G42Fvo15z4bG2X8D2GhfbSXc/readme
      - name: Replicate git repository and unpack objects
        run: |
          git clone file://$PWD/.git/ --bare ytdl-patched
          cd ytdl-patched
          git update-server-info
          mv objects/pack/pack-* .
          find . -name 'pack-*.pack' -type f -exec bash -c 'git unpack-objects < {}' \;
          rm -rf pack-* objects/pack/
          git count-objects -v
      - name: Upload to IPFS
        run: |
          ipfs add -r ytdl-patched/ | tee upload.log
          tail -n1 upload.log | awk '{ print $2 }'
