name: Upload to IPFS

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs: {}

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master
      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Install IPFS
        run: |
          sudo apt install -y snapd
          sudo snap install ipfs
          ipfs init
          ipfs cat /ipfs/QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG/quick-start

